package GoToJava

import java.io.BufferedReader

val ptrMap: MutableMap<Int, Any> = mutableMapOf()
val mapDec: Map<String, (BufferedReader, Int)->Any?> = mapOf(
    "Int" to ::readInteger,
    "Short" to ::readInteger,
    "Long" to ::readInteger,
    "Float" to ::readReal,
    "Double" to ::readReal,
    "String" to ::readString,
    "Boolean" to ::readBoolean,
    "nil" to ::readNil,

    "array" to ::readArray,
    "map" to ::readMap,
	"types_object" to ::read_types_object,
	"ast_Ident" to ::read_ast_Ident,
	"types_monoVertex" to ::read_types_monoVertex,
	"generatedInlineStruct_000" to ::read_generatedInlineStruct_000,
	"ast_DeclStmt" to ::read_ast_DeclStmt,
	"types_Nil" to ::read_types_Nil,
	"ast_BinaryExpr" to ::read_ast_BinaryExpr,
	"ssa_BinOp" to ::read_ssa_BinOp,
	"types_Selection" to ::read_types_Selection,
	"types_Term" to ::read_types_Term,
	"types_environment" to ::read_types_environment,
	"ssa_Parameter" to ::read_ssa_Parameter,
	"ssa_Program" to ::read_ssa_Program,
	"ast_TypeSpec" to ::read_ast_TypeSpec,
	"ast_FieldList" to ::read_ast_FieldList,
	"token_File" to ::read_token_File,
	"ssa_selection" to ::read_ssa_selection,
	"ast_AssignStmt" to ::read_ast_AssignStmt,
	"ssa_BasicBlock" to ::read_ssa_BasicBlock,
	"types_Builtin" to ::read_types_Builtin,
	"ssa_Store" to ::read_ssa_Store,
	"ssa_Const" to ::read_ssa_Const,
	"atomic_Int32" to ::read_atomic_Int32,
	"types_Context" to ::read_types_Context,
	"types_Var" to ::read_types_Var,
	"types_instance" to ::read_types_instance,
	"ssa_Jump" to ::read_ssa_Jump,
	"ast_UnaryExpr" to ::read_ast_UnaryExpr,
	"ssa_CallCommon" to ::read_ssa_CallCommon,
	"types_action" to ::read_types_action,
	"types_Instance" to ::read_types_Instance,
	"ast_BasicLit" to ::read_ast_BasicLit,
	"ast_FuncDecl" to ::read_ast_FuncDecl,
	"types_instanceLookup" to ::read_types_instanceLookup,
	"sync_Mutex" to ::read_sync_Mutex,
	"types_Signature" to ::read_types_Signature,
	"types_Checker" to ::read_types_Checker,
	"types_dotImportKey" to ::read_types_dotImportKey,
	"types_Package" to ::read_types_Package,
	"types_Pointer" to ::read_types_Pointer,
	"ast_Field" to ::read_ast_Field,
	"ssa_generic" to ::read_ssa_generic,
	"typeutil_entry" to ::read_typeutil_entry,
	"ssa_typeListMap" to ::read_ssa_typeListMap,
	"types_Union" to ::read_types_Union,
	"types_Tuple" to ::read_types_Tuple,
	"types_Label" to ::read_types_Label,
	"types_Scope" to ::read_types_Scope,
	"ast_SelectorExpr" to ::read_ast_SelectorExpr,
	"ast_FuncType" to ::read_ast_FuncType,
	"types_PkgName" to ::read_types_PkgName,
	"ast_ImportSpec" to ::read_ast_ImportSpec,
	"ssa_If" to ::read_ssa_If,
	"ast_GenDecl" to ::read_ast_GenDecl,
	"types_TypeParam" to ::read_types_TypeParam,
	"types_Info" to ::read_types_Info,
	"types_version" to ::read_types_version,
	"types_MethodSet" to ::read_types_MethodSet,
	"types_Named" to ::read_types_Named,
	"types_Basic" to ::read_types_Basic,
	"ssa_register" to ::read_ssa_register,
	"token_FileSet" to ::read_token_FileSet,
	"ast_File" to ::read_ast_File,
	"ssa_FreeVar" to ::read_ssa_FreeVar,
	"ast_ValueSpec" to ::read_ast_ValueSpec,
	"types_importKey" to ::read_types_importKey,
	"types_term" to ::read_types_term,
	"ssa_lblock" to ::read_ssa_lblock,
	"types_Interface" to ::read_types_Interface,
	"sync_RWMutex" to ::read_sync_RWMutex,
	"types_monoEdge" to ::read_types_monoEdge,
	"ast_CallExpr" to ::read_ast_CallExpr,
	"generatedInlineStruct_001" to ::read_generatedInlineStruct_001,
	"ast_ExprStmt" to ::read_ast_ExprStmt,
	"types_TypeAndValue" to ::read_types_TypeAndValue,
	"types__TypeSet" to ::read_types__TypeSet,
	"ssa_canonizer" to ::read_ssa_canonizer,
	"typeutil_Hasher" to ::read_typeutil_Hasher,
	"ast_CommentGroup" to ::read_ast_CommentGroup,
	"ssa_Alloc" to ::read_ssa_Alloc,
	"ssa_Global" to ::read_ssa_Global,
	"ssa_Builtin" to ::read_ssa_Builtin,
	"ssa_UnOp" to ::read_ssa_UnOp,
	"ssa_RunDefers" to ::read_ssa_RunDefers,
	"types_Func" to ::read_types_Func,
	"ssa_domInfo" to ::read_ssa_domInfo,
	"types_TypeParamList" to ::read_types_TypeParamList,
	"types_declInfo" to ::read_types_declInfo,
	"ssa_targets" to ::read_ssa_targets,
	"ast_ReturnStmt" to ::read_ast_ReturnStmt,
	"types_Config" to ::read_types_Config,
	"ast_Comment" to ::read_ast_Comment,
	"ast_Object" to ::read_ast_Object,
	"types_monoGraph" to ::read_types_monoGraph,
	"ssa_tpWalker" to ::read_ssa_tpWalker,
	"sync_Once" to ::read_sync_Once,
	"typeutil_Map" to ::read_typeutil_Map,
	"types_Const" to ::read_types_Const,
	"token_lineInfo" to ::read_token_lineInfo,
	"ast_BlockStmt" to ::read_ast_BlockStmt,
	"types_actionDesc" to ::read_types_actionDesc,
	"ssa_subster" to ::read_ssa_subster,
	"types_TypeName" to ::read_types_TypeName,
	"types_exprInfo" to ::read_types_exprInfo,
	"ssa_Return" to ::read_ssa_Return,
	"ssa_Package" to ::read_ssa_Package,
	"types_TypeList" to ::read_types_TypeList,
	"types_Initializer" to ::read_types_Initializer,
	"ast_IfStmt" to ::read_ast_IfStmt,
	"ssa_Call" to ::read_ssa_Call,
	"ssa_Function" to ::read_ssa_Function,
	"types_ctxtEntry" to ::read_types_ctxtEntry,
	"ast_Scope" to ::read_ast_Scope,
	"typeutil_MethodSetCache" to ::read_typeutil_MethodSetCache
)

fun StartDeserializer(buffReader: BufferedReader): Any? {
    val line = buffReader.readLine()
    val split = line.split(" ")
    val readType = split[0]
    var id = -1
    if (split.size > 1) {
        id = split[1].toInt()
    }
    return mapDec[readType]?.invoke(buffReader, id)
}
